name: artic
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - artic-porechop==0.3.2pre
  - artic-tools==0.2.6
  - bcftools=1.10.2
  - biopython=1.76
  - bwa=0.7.17
  - clint=0.5.1
  - htslib=1.10.2
  - longshot=0.4.1
  - medaka=1.0.3
  - minimap2=2.22
  - multiqc
  - muscle=3.8
  - nanopolish=0.13.2
  - nomkl
  - pandas=0.23.0
  - pip
  - pysam=0.16.0.1
  - pytest
  - python=3.6
  - pyvcf=0.6.8
  - samtools=1.10
  - tqdm
