site_name: artic pipeline
repo_url: https://github.com/artic-network/fieldbioinformatics
theme: readthedocs
nav:
  - Home: "index.md"
  - "User Guide":
      - "Installation": "installation.md"
      - "Quick Start": "quick-start.md"
      - "Commands": "commands.md"
      - "Tests": "tests.md"
  - About:
      - "FAQ": "faq.md"
      - "Primer Schemes": "primer-schemes.md"
      - "Core Pipeline": "minion.md"
      - "License": "license.md"
      - "Release Notes": "release-notes.md"
markdown_extensions:
  - admonition
  - codehilite
